### ISSUE TITLE
 non-integer slice index "Serial Number"

### ISSUE THREAD

**Issue by d1rtyb1t** [square/luks2crypt#4]
I keep getting this error when trying to build the luks2crypt package.

/usr/lib/golang/src/github.com/square/luks2crypt/hwinfo/hwinfo.go:36:19: non-integer slice index "Serial Number"
/usr/lib/golang/src/github.com/square/luks2crypt/hwinfo/hwinfo.go:36:19: cannot use byNameData["Serial Number"] (type dmidecode.Record) as type string in return argument
Clayton

**Comment by d1rtyb1t** [comment]
Its on Centos 7.5 machine..

**Comment by derektamsen** [comment]
@d1rtyb1t have you resolved the build issue? I haven't tested building luks2crypt against CentOS/RHEL at this point so I am not quite sure what issues may exist.
