### ISSUE TITLE
Ubuntu v20.04.1 - error with code -22

### ISSUE THREAD

**Issue by amadotejada** [square/luks2crypt#57]
Hello!

Thank you for creating this tool. I noticed an error code -22 when trying to escrow the key. I'm running an Ubuntu 20.04 VM.

Being 20.04 was released last year, does this tool supports luk2 and Ubuntu 20.04?

Thank you!

Running latest crypt server version and below
```
sudo luks2crypt postimaging \
  --luksdevice "/dev/sda6" \
  --currentpassword "test" \
  --cryptserver "http://IP:8000" \
  --authuser "admin" \
  --authpass "password"
```

Output
```
021/02/04 14:58:58 {SerialNum:VMware-45478 Hostname:name-147e01 Username:root}
2021/02/04 14:58:58 generated new random password
error setting escrow passphrase: crypt_load returned error with code -22
```

**Comment by amadotejada** [comment]
Update: I compiled the pending pull request and the binary worked under Ubuntu 20.04.1 - luks2

**Comment by derektamsen** [comment]
@amadotejada I am happy to hear you were able to build the patch in #56. Before merging #56 I need to work on the tests as the PR breaks them. Unfortunately, I have not had much time to look at it.

**Comment by derektamsen** [comment]
@amadotejada `luks2crypt` now has an official build with support for luks2 and ubuntu 20.04 focal in release [v0.4.0](https://github.com/square/luks2crypt/releases/tag/v0.4.0).

**Comment by amadotejada** [comment]
Amazing! 🙏🏽
