### ISSUE TITLE
Client version in Ubuntu 18.04

### ISSUE THREAD

**Issue by davidkast** [square/luks2crypt#66]
Hello,
thanks for this great project, a question:
[Version 0.3.1](https://github.com/square/luks2crypt/releases/tag/v0.3.1) is compatible with Ubuntu 18.04, but if I try to apply the latest version 0.4.1 it doesn't work, is this correct?

The error is as follows:
error setting escrow passphrase: crypt_load returned error with code -22

Regards.

**Comment by derektamsen** [comment]
@davidkast You're welcome! It should still be compatible with Ubuntu 18.04. Version 0.4.1 of luks2crypt in github releases is built against cryptsetup 2.2.2 in Ubuntu 20.04 which is newer than the version Ubuntu 18.04 ships with. The cryptsetup library had a major change between the two Ubuntu versions. To enable support in luks2crypt against the older library their is a [luks version flag](https://github.com/square/luks2crypt/blob/main/cmd/luks2crypt/main.go#L48) in luks2crypt.

Can you try running `luks2crypt` with your normal flags but add `--luksversion 1` or `-v 1`?

Example:

```
sudo luks2crypt postimaging \
  --luksdevice "<device_to_manage>" \
  --currentpassword "<password_to_replace>" \
  --cryptserver "<cryptserver.example.com>" \
  --luksversion 1
```

**Comment by davidkast** [comment]
Hello,
now if it works, thank you very much I did not know the parameter you indicate, I have not seen it in the documentation.

When to use --luksVersion 1 or --luksVersion 2?

Greetings.

**Comment by derektamsen** [comment]
Great! Glad to hear it is working. The luks version flag is a new feature and is not in the documentation yet. I will open a ticket to update the docs to include the option.

> When to use --luksVersion 1 or --luksVersion 2?

The version you specify in the flag is related to the version of the luks header on the encrypted device. On newly installed Ubuntu 20.04 systems this will be 2 and on Ubuntu 18.04 this will be 1. If you upgraded an Ubuntu 18.04 system to 20.04 the luks header version will still be version 1 unless you specifically upgrade the luks device. You can view the luks device version with `sudo cryptsetup luksDump /dev/<encrypted_device>`.
